### ISSUE TITLE
Problema com comentários grandes

### ISSUE THREAD

**Issue by Valgueiro** [Projetao-2019-2/toth-ui#13]
Relato de markeka (duvidas falar com ele):

> fiz um comentário gigante nesse aí, postei e não aconteceu nada
> aí escrevo "eqwewq" aperto enter e aparece
> pensei que foi porque escrevi muito
> mas aí coloquei um grandinho lá tbm e foi

Pode ser que seja um problema de back. Se for o caso, mandar essa issue para @Zambom

**Comment by pedrohlscin** [comment]
Então, aparentemente o problema é para comentários que mais que 250 caracteres, vai alterar no back pra permitir mais ou isso ai já é ok?
