### ISSUE TITLE
Fazer tela de profile para outros usuários.

### ISSUE THREAD

**Issue by Valgueiro** [Projetao-2019-2/toth-ui#20]
Atualmente a tela de profile só mostra o perfil de quem está logado.

TO-DO:
Devemos transformar a tela que está implementada agora para a rota /profile/me e criar uma nova que será igual a já implementada mas receberá um `id` do usuário (/profile/_id). A tela deve mostrar os dados do usuário e os posts criados por ele.

**Comment by Valgueiro** [comment]
Dica: ver a implementação da tela de detalhes de posts (pages/posts/_id). A implementaçao deve ser muito parecida.

**Comment by abcr98** [comment]
Tu saberia dizer qual o mockup relacionado a essa tela? Não entendi muito bem qual a mudança que deve ser feita quanto ao que é exibido na tela atual
