### ISSUE TITLE
Mostrar posts baseado na quantidade de votos

### ISSUE THREAD

**Issue by Valgueiro** [Projetao-2019-2/toth-ui#25]
Os resultados da pesquisas devem ser ranqueados antes de ser mostrado para o usuário.

Acredito que seja uma task de back-end, mas é importante falar com erik antes

**Comment by Zambom** [comment]
Hoje a busca é ordenada (no back) pelo número de "util" [do maior pro menor]; depois pelo número de "n_util" [do menor pro maior]; por fim pelo id [do maior pro menor] (seria equivalente à ordenar pela data de criação).

**Comment by Valgueiro** [comment]
Opa, nao sabia disso. Entao, como nao mexemos na ordem dos posts no front, já está na ordem correta.
